### ISSUE TITLE
The file can't open

### ISSUE THREAD

**Issue by Minorlovania** [HiDe-Techno-Tips/Mouse2Gamepad_for_Yuzu#4]
well, I have auto hotkey installed because the program was a script and wasn't compelled, so when I tried to open it to compile it into a .exe the file couldn't oppen

**Comment by HiDe-Techno-Tips** [comment]
https://github.com/HiDe-Techno-Tips/Mouse2Gamepad_for_Yuzu/releases/latest/download/Mouse2Gamepad_for_Yuzu.zip

The above link will download the zip file that contains the precompiled exe file. Download it and then follow the steps found in the below link:

https://github.com/HiDe-Techno-Tips/Mouse2Gamepad_for_Yuzu#how-to-use
